manage process

diff --git a/processes_and_signals/11-manage_my_process b/processes_and_signals/11-manage_my_process
--- a/processes_and_signals/11-manage_my_process
+++ b/processes_and_signals/11-manage_my_process
@@ -1,31 +1,45 @@
 #!/usr/bin/env bash
-# Init script to manage manage_my_process
+# manages manage_my_process
+# Check if an argument is provided
+# Check if an argument is provided
+if [ -z "$1" ]; then
+    echo "Usage: manage_my_process {start|stop|restart}"
+    exit 1
+fi
 
+# Check the provided argument
 case "$1" in
     start)
         ./manage_my_process &
-        echo $! > /var/run/my_process.pid
+        echo "$!" > /var/run/my_process.pid
         echo "manage_my_process started"
         ;;
     stop)
         if [ -f /var/run/my_process.pid ]; then
+            echo "manage_my_process stopped"
             kill "$(cat /var/run/my_process.pid)"
             rm /var/run/my_process.pid
+        else
+            echo "PID file not found. manage_my_process might not be running."
         fi
-        echo "manage_my_process stopped"
         ;;
     restart)
         if [ -f /var/run/my_process.pid ]; then
+            echo "manage_my_process restarted"
             kill "$(cat /var/run/my_process.pid)"
             rm /var/run/my_process.pid
+            ./manage_my_process &
+            echo "$!" > /var/run/my_process.pid
+        else
+            echo "PID file not found. Starting manage_my_process."
+            ./manage_my_process &
+            echo "$!" > /var/run/my_process.pid
         fi
-        ./manage_my_process &
-        echo $! > /var/run/my_process.pid
-        echo "manage_my_process restarted"
         ;;
     *)
-        echo "Usage: manage_my_process {start|stop|restart}"
+        echo "Usage: $0 {start|stop|restart}"
         exit 1
         ;;
 esac
-                    
+
+exit 0                    
